name: Feature Request
description: Request a new feature or enhancement to the Package
title: "[feature]: "
labels: ["feature"]
body:
  - type: textarea
    id: description
    attributes:
      label: Feature request
      description: Please describe the feature you would like to see added to the package.
      placeholder: I would like to see X feature added to the package.
    validations:
      required: true
